### ISSUE TITLE
Which version of sally is supposed to work with which version of PRISM ?

### ISSUE THREAD

**Issue by dohmatob** [tammok/PRISMA#1]
It seems sally and PRISM are totally out of sync. I couldn't find any doc telling me which version of sally is required for working with PRISM (for example loading asap data)

```
Error: Your configuration is missing the new 'granularity' parameter. Please consult the manual page and upgrade your configuration. (sally_load_config)
```

**Comment by rieck** [comment]
You have two options: 
- PRISMA has been developed in 2011. I am sure that a Sally version from that time will work.
- You can adapt PRISMA to the new command-line options of Sally. Should not be too difficult.

**Comment by dohmatob** [comment]
OK, thanks. I'll try the above workarounds and let you know how it goes.

This (PRISMA) is probably excellent software, but  such glitches can ruin a user new to the code base. Documenting versions, compat stuff, etc., somewhere (in the README ?) would be incredibly useful :)

**Comment by rieck** [comment]
Welcome to the world of open-source software, where every user is a developer.

**Comment by dohmatob** [comment]
@rieck: this was obviously meant to be a joke (since I'm in the open-source business too) :)

**Comment by dohmatob** [comment]
FWIW: My `git bisect` tells me the commit 96c9e6741400a6003e56deace54ffccce114d4ea is the last commit which still supported the PRISM asap conf file format. I'll just roll-back to this version. A quick-and-dirty walkaround for the user would be backtrack to this old commit hash.
