### ISSUE TITLE
Index larger than maximal 0 error

### ISSUE THREAD

**Issue by valour01** [tammok/PRISMA#2]
Hi, I am using PRISMA to load data, when I use the function `loadPrismaData`, I come up with the exception below

```
> data = loadPrismaData(capture_dir)
Reading data...
Splitting ngrams...
Calc indices...
Setup matrix...
to check: 2 
Error in intI(i, n = x@Dim[1], dn[[1]], give.dn = FALSE) : 
index larger than maximal 0
Calls: loadPrismaData ... callGeneric -> eval -> eval -> [ -> [ -> subCsp_rows -> intI
Execution halted
```

Do you know what the cause is. I noticed the program crashed at `curCor = sparse.cor(mat[toCheck, ])`. I was wondering whether you need more information or you can give me some suggestions. Many Thanks

**Comment by tammok** [comment]
Hi, it seems that the data matrix passed to `sparse.cor` has no features, i.e. it is a "0 x number of documents" matrix. This will result in a not really meaningful row-index vector `toCheck = [1 0]` which leads to the error message when executing `mat[toCheck, ]`. You can skip the feature correlation step by using `data = loadPrismaData(capture_dir, skipFeatureCorrelation=TRUE)` which should at least prevent the error. But I assume that there is something wrong with the pcap files and/or generated sally files you are using... perhaps @hgascon has some insights?

**Comment by RoelVdP** [comment]
Just for reference, the proposed change is this;

```
diff --git a/pulsar/core/cluster_generator.R b/pulsar/core/cluster_generator.R
index 1a99f1a..4dd0048 100644
--- a/pulsar/core/cluster_generator.R
+++ b/pulsar/core/cluster_generator.R
@@ -22,7 +22,8 @@ source("matrixFactorization.R")
 setwd(initial_dir)
 
 # load the dataset
-data = loadPrismaData(capture_dir)
+#data = loadPrismaData(capture_dir)
+data = loadPrismaData(capture_dir, skipFeatureCorrelation=TRUE)
 
 # estimate number of components
 #dim = calcEstimateDimension(data$unprocessed)
```

But this may not eliminate the underlying problem of there not being meaningful data in the pcap file

**Comment by RoelVdP** [comment]
Related https://github.com/hgascon/pulsar/issues/2#issue-148835422
